= Getting started with Laravel
Stevan Vlajic
1.0.0, {docdate}: Praktikum
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:


//Need this blank line after ifdef, don't know why...

// print the toc here (not at the default position)
//toc::[]

== How to install

[source, bash]
----
composer create-project --prefer-dist laravel/laravel name
----

== How to start local-dev server

[source, bash]
----
php artisan serve
----

== Wichtige directories

* `/resources/views` -> eine view kann in der get route per `/hallo` zugewiesen hierbei ist du beachte, dass die view den namen hallo.php hat. demnach ist die datei die vom server im endeffekt interpretiert wird unter `/resources/views` zu finden. diese datei würde demnach `hallo.blade.php` heißen
* `/routes/web.php` alle requests ->

Beispiel:
[source, PHP]
----
Route::get('/', function () {
    return "hallo welt";
    // return view('welcome');
});

Route::get('/hallo', function () {
    return view('hallo');
});
----

== Dynamische Routen
[source, PHP]
----
Route::get('/user/{name}', function ($name) {
    return "Hallo " . $name;
});

Route::get('/user/{name}/{lastname}', function ($name, $lastname) {
    return "Hallo " . $name ." " . $lastname;
});
----

== GET parameter auslesen
[source, PHP]
----
Route::get('/products', function (){
    $id = request('id');
    echo "here is your product with the id: " . $id;
});
----
* http://localhost:8000/products?id=124

== Erstellen von VIEWS

* `/resources/views/...` -> user.php

Views zurück geben:

[source, PHP]
----
Route::get('/user', function () {
    return view('user');
});
----

== Parameter für VIEWS mitgeben

* `/resources/views/...` -> user.php

* PHP

[source, PHP]
----
Route::get('/user', function () {
    $id = request('id');
    $name = request('name');
    $lastname = request('lastname');

    return view('user',[
        'id' => $id,
        'name' => $name,
        'lastname' => $lastname
    ]);
});
----

* HTML:

[source, HTML]
----
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Document</title>
</head>
<body>
    <h1>Ich bin eine simple user view... :)</h1>
    <h1>Du bist folgender user: <?php echo $id. ": " . $name . " " .$lastname; ?></h1>
</body>
</html>
----


* `/resources/views/...` -> user.blade.php

[source, HTML]
----
<h1>Du bist folgender user: {{$id}} {{$name}} {{$lastname}}</h1>
----

== Controller erstellen zum auslagern der Logik

* Controller erstellen:
** `php artisan make:controller ...` -> UserController
** `php artisan make::controller NewsController --resource` -> Controller mit all dem SchnickSchnak den man so braucht

* `/app/Http/Controllers/UserController.php`

[source,  PHP]
----
  public function show(){
        return 'Hallo aus dem Controller';
    }
----

* `/routes/web.php`

[source,  PHP]
----
Route::get('/info', [InfoController::class, 'show']);
Route::get('/news/{id}', [NewsController::class, 'show']); # pass param to the controller
----

== Laravel Filament install

* `laravel new filament-test --jet`
* `composer require laravel/breeze --dev`
* `php artisan breeze:install` 
* `php artisan migrate`
* `php artisan serve`
* `composer require filament/filament:"^2.0"`


[source,  BASH]
----
"post-update-cmd": [
    // ...
    "@php artisan filament:upgrade"
],
----

* `php artisan make:filament-user`


=== Migrations Refresh
* `php atrisan migrate:refresh`

=== Resources
* Resources sind zum Managen vom models
** `php artisan make:filament-resource Customer` 

=== Models
* Datenmodel wird in filament als Model erstellt
* `php artisan make:model Country -m`
* `php artisan make:model Country -m`
* ...

=== Workflow
* Datenmodell
* Model erstellen
* Migrations bearbeiten -> an ERD anpassen
* Resources bearbeiten
* Nach dem Model alles migrieren
* Model bearbeiten


=== Add groups
* `protected static ?string $navigationGroup = 'User Management';`
* On top of a Resource

=== Icons
* `protected static ?string $navigationIcon = `
*  On top of resources
* Icons can be found under: `https://heroicons.com/`
* Example:     
** `protected static ?string $navigationIcon = 'heroicon-o-arrow-down-right';`

=== Order groups
* `protected static ?int $navigationSort = 1;`
* Add it to every resource 

=== Custom Widgets
* `php artisan make:filament-widget CustomerOverview --resource=CustomerResource`
* `php artisan make:filament-widget UserStatsOveriew --stats-overview`
* Edit list under /pages/Listusers


=== Cards
* `https://filamentphp.com/docs/2.x/admin/dashboard/stats`

[source, PHP]
-----
 Card::make('People Count', $people_count)
                ->icon("heroicon-o-users")
            ->description("Wie viele Mitarbeiter hat das Unternehmen zurzeit?")
            ->descriptionIcon('heroicon-o-trending-up'),

-----


[source, PHP]
-----

    protected function getHeaderWidgets(): array
    {
        return [
            UserOverview::class,
        ];
    }

-----

==== Dashboard Widget
* `php artisan make:filament-widget Dasboard/PeopleCount --stats-overview`

[source, PHP]
-----
protected function getCards(): array
    {
        $people_count = People::all()->count();
        $user_count = User::all()->count();


        return [
            Card::make('People Count', $people_count)
        ];
    
-----


=== Resources Widgets
* `php artisan make:filament-widget PeopleOverview --stats-overview`
* Implementieren von Crads im PeopleOverview
* ListPeople:

[source, PHP]
----
 protected function getHeaderWidgets(): array
    {
        return [PeopleOverview::class];
    }

----

* People Resource:

[source, PHP]
-----
 public static function getWidgets(): array
    {
        return [
            PeopleOverview::class,
        ];
    }
-----

* https://filamentphp.com/docs/2.x/admin/resources/widgets


== Adding Custom SEARCHBAR
* In some resource file
* `protected static ?string $recordTitleAttribute = 'name';`

== Change Navigation props
* `protected static ?string $navigationIcon = 'heroicon-o-document-text';`
* `protected static ?string $navigationLabel = 'Custom Navigation Label';`
* `protected static ?int $navigationSort = 3;`

== Custom Label

[source, PHP]
-----
  public static function getNavigationLabel(): string
    {
        return 'Ich bin ein custom label';
    }
-----

=== Notifications
* https://filamentphp.com/docs/2.x/notifications/sending-notifications 
* unter /pages/editPeople.class oder so 

=== Image Upload

[source, PHP]
-----
FileUpload::make('image_path')
                    ->columns(1)
                    ->directory('test-images')
-----

=== Tailwind themes
* app/Providers/Filament/AdminPanelProvider.php



=== Startup project
* git clone 
* composer install
* php artisan key:generate
* php artisan migrate --seed
* php artisan migrate:fresh --seed
* http://stiftung.test/admin
